Fix/param namespace association 894
ros2/rclpy pull request #1132
Opened 2023-06-07 15:17 UTC by devrite

Fixes #894

2023-06-07 17:07 UTC, fujitatomoya approved these changes
lgtm, @devrite thanks for the contribution.

@jacobperron can you do another review?

2023-06-14 14:24 UTC, clalancette requested changes

2023-06-14 14:24 UTC, clalancette commented on rclpy/rclpy/node.py
> +            validate_parameter_name(name)
I think we need to move a bit more code around.  In particular, if `parameter_tuple[0]` was not passed as a `string`, then we could potentially have an issue here.  I'll suggest that we move the `if not isinstance(name, str)` check from lines 464 below to right after we assign `parameter_tuple[0]` to `name`.

2023-06-14 16:24 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18953)](http://ci.ros2.org/job/ci_linux/18953/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13485)](http://ci.ros2.org/job/ci_linux-aarch64/13485/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19706)](http://ci.ros2.org/job/ci_windows/19706/)

2023-06-14 19:09 UTC, clalancette commented
@devrite Due to some unrelated changes, this needs to be rebased onto the `rolling` branch to pass CI.  Let me know once you've done that and I'll kick off another round.

2023-06-14 20:56 UTC, devrite commented
Cleared for launch!

2023-06-15 17:53 UTC, merged