[Humble] Fix AttributeError _logger in Action Server
ros2/rclpy pull request #1299
Opened 2024-06-14 18:09 UTC by sloretz

Fix bug in Humble reported here: https://github.com/ros2/rclpy/pull/982#issuecomment-2145899244

I decided not to backport #982 to avoid the new sublogger affecting someone's filtering of the log messages in Humble. I checked and this bug does not affect Iron.

2024-06-14 19:47 UTC, ahcorde requested changes
Some flake8 linters errors https://build.ros2.org/job/Hpr__rclpy__ubuntu_jammy_amd64/41/

2024-06-14 19:59 UTC, fujitatomoya reviewed
@sloretz thanks for the fix, lgtm with flake8 errors fixes.

2024-06-17 08:18 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21275)](http://ci.ros2.org/job/ci_linux/21275/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15595)](http://ci.ros2.org/job/ci_linux-aarch64/15595/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=773)](http://ci.ros2.org/job/ci_linux-rhel/773/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22003)](http://ci.ros2.org/job/ci_windows/22003/)

2024-06-17 21:58 UTC, sloretz commented
Retrying RHEL job with [RHEL 8](https://www.ros.org/reps/rep-2000.html#humble-hawksbill-may-2022-may-2027)

[![Build Status](https://ci.ros2.org/job/ci_linux-rhel/774/badge/icon)](https://ci.ros2.org/job/ci_linux-rhel/774/)

2024-06-21 17:53 UTC, sloretz commented
Learned RHEL 8 Humble job hanging tests is a known issue.

2024-06-21 17:53 UTC, merged