Add types to wait_for_message.py
ros2/rclpy pull request #1325
Opened 2024-07-31 15:53 UTC by InvincibleRMC

This pull request adds types to wait_for_message.py. It also creates the `WaitSetHandle`. The `WaitSetHandle` needed some not yet implemented Handles so I implemented some dummy Handles in the interim until the Handles get implemented.

2024-08-20 23:44 UTC, sloretz requested changes
LGTM with on nitpick addressed

2024-08-20 23:44 UTC, sloretz commented on rclpy/rclpy/wait_for_message.py
> +        raise Exception('Cannot create Waitset without a context.handle')
Nit, please use `RuntimeError` here.

2024-08-21 16:47 UTC, sloretz approved these changes

2024-08-21 21:25 UTC, sloretz commented
Pulls: ros2/rclpy#1325
Gist: https://gist.githubusercontent.com/sloretz/e11b408ea5abaf83d4be1cab5bdf4568/raw/e737363e25007355832cccf984cd87285e962c19/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14436
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21704)](http://ci.ros2.org/job/ci_linux/21704/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15978)](http://ci.ros2.org/job/ci_linux-aarch64/15978/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1209)](http://ci.ros2.org/job/ci_linux-rhel/1209/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22408)](http://ci.ros2.org/job/ci_windows/22408/)

2024-08-21 21:27 UTC, sloretz commented
@mergifyio update

2024-08-21 21:28 UTC, sloretz commented
Pulls: ros2/rclpy#1325
Gist: https://gist.githubusercontent.com/sloretz/62f40dc912a8c6d90383b8b429f90d84/raw/e737363e25007355832cccf984cd87285e962c19/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14437
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21705)](http://ci.ros2.org/job/ci_linux/21705/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15979)](http://ci.ros2.org/job/ci_linux-aarch64/15979/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1210)](http://ci.ros2.org/job/ci_linux-rhel/1210/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22409)](http://ci.ros2.org/job/ci_windows/22409/)

2024-08-21 21:57 UTC, InvincibleRMC commented
There seems to be a merge problem I will fix when I get a chance.

2024-08-22 20:31 UTC, sloretz approved these changes

2024-08-22 20:32 UTC, sloretz commented
@mergifyio update

2024-08-22 20:33 UTC, sloretz commented
Pulls: ros2/rclpy#1325
Gist: https://gist.githubusercontent.com/sloretz/f76824db58100e24ade28109e5780bfb/raw/e737363e25007355832cccf984cd87285e962c19/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14456
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21725)](http://ci.ros2.org/job/ci_linux/21725/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16000)](http://ci.ros2.org/job/ci_linux-aarch64/16000/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1230)](http://ci.ros2.org/job/ci_linux-rhel/1230/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22428)](http://ci.ros2.org/job/ci_windows/22428/)

2024-08-23 16:22 UTC, merged