Adds types to Lifecycle Objects
ros2/rclpy pull request #1338
Opened 2024-08-22 18:31 UTC by InvincibleRMC

Builds off of #1235.

2024-08-23 18:13 UTC, sloretz requested changes
LGTM with one nitpick!

2024-08-23 18:13 UTC, sloretz commented on rclpy/rclpy/lifecycle/node.py
> +            raise Exception('Node failed to create LifecyclePublisher.')
nit, please use RuntimeError

2024-08-26 18:45 UTC, sloretz approved these changes

2024-08-26 18:45 UTC, sloretz commented
@mergifyio update

2024-08-26 18:49 UTC, sloretz commented
Pulls: ros2/rclpy#1338
Gist: https://gist.githubusercontent.com/sloretz/5ae8c9493cbb2f6cd304e97a2d4ef14c/raw/0cc08b8cc6fe2a9191ebc2969ec1ba7b33589bc5/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14473
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21743)](http://ci.ros2.org/job/ci_linux/21743/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16017)](http://ci.ros2.org/job/ci_linux-aarch64/16017/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1248)](http://ci.ros2.org/job/ci_linux-rhel/1248/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22446)](http://ci.ros2.org/job/ci_windows/22446/)

2024-08-26 21:55 UTC, sloretz approved these changes

2024-08-26 21:57 UTC, sloretz commented
Pulls: ros2/rclpy#1338
Gist: https://gist.githubusercontent.com/sloretz/26afab0411e269cd97f9c479b0507b67/raw/0cc08b8cc6fe2a9191ebc2969ec1ba7b33589bc5/ros2.repos
BUILD args:  --packages-above-and-dependencies rclpy
TEST args:  --packages-above rclpy
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14474
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21744)](http://ci.ros2.org/job/ci_linux/21744/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16018)](http://ci.ros2.org/job/ci_linux-aarch64/16018/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1249)](http://ci.ros2.org/job/ci_linux-rhel/1249/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22447)](http://ci.ros2.org/job/ci_windows/22447/)

2024-08-30 18:32 UTC, sloretz commented
@InvincibleRMC Mind fixing the conflict in this one?

2024-09-04 15:21 UTC, InvincibleRMC commented
@sloretz The conflicts have been fixed.

2024-10-04 04:45 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21945)](http://ci.ros2.org/job/ci_linux/21945/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16212)](http://ci.ros2.org/job/ci_linux-aarch64/16212/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1462)](http://ci.ros2.org/job/ci_linux-rhel/1462/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22672)](http://ci.ros2.org/job/ci_windows/22672/)

2024-10-04 19:07 UTC, ahcorde approved these changes

2024-10-04 19:08 UTC, merged