fix _get_parameter_types_callback Enum to ParameterType conversion
ros2/rclpy pull request #620
Opened 2020-09-13 10:28 UTC by nyxaria

As discussed in #618, this fixes the conversion from Python Enum type to the `int` type in `ParameterType.msg`.

Before:
```parameter_service.py", line 90, in _get_parameter_types_callback
    response.types.append(node.get_parameter_or(name).type_)
TypeError: an integer is required (got type Type)```

2020-09-14 13:25 UTC, clalancette requested changes
Can you please add a test (either to [test_parameter.py](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_parameter.py) or [test_parameters_callback.py](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_parameters_callback.py)) to ensure that this is doing what we expect?  Thanks.

2020-09-21 23:17 UTC, nyxaria commented
I will try to do this in the following week, moving houses at the moment and swamped with work so I have no time to fix this now. Apologies for the delays.

2020-09-22 13:09 UTC, clalancette commented
@nyxaria No problem, thanks for the heads up.

2020-10-08 13:10 UTC, clalancette commented
@nyxaria Hope your house moving went well.  Friendly ping to add a test here, thanks.

2020-12-23 00:07 UTC, sloretz commented
Oops, it looks like someone opened a duplicate PR and it got merged (#641). Thanks for the PR!  Closing.

2020-12-23 00:07 UTC, closed without merging