Use py::class_ for rcl_action_goal_handle_t
ros2/rclpy pull request #751
Opened 2021-04-02 02:20 UTC by gbalke

Part of #665.

2021-04-02 10:25 UTC, ahcorde commented on rclpy/src/rclpy/action_goal_handle.cpp
> +    "Destroy a goal handle.");
you should remove this because it's an overridden method, it should be registered.

2021-04-02 10:26 UTC, ahcorde commented on rclpy/rclpy/action/server.py
> +            self._goal.destroy()
```suggestion
            self._goal.destroy_when_not_in_use()
```

2021-04-05 21:39 UTC, gbalke commented
In a certain condition, the state of an `allocator` assigned to the goal handle is a null pointer. In this scenario, the de-allocate call inside of the `fini` causes a segfault. I'm still uncertain as to if this is a `rcl` bug or an `rclpy` issue.

2021-04-06 02:38 UTC, gbalke commented
@ros-pull-request-builder retest this

2021-04-06 17:20 UTC, gbalke commented
@ros-pull-request-builder retest this

2021-04-06 17:24 UTC, hidmic commented on rclpy/src/rclpy/action_goal_handle.cpp
> +  rcl_action_goal_handle_ = std::make_shared<rcl_action_goal_handle_t>(*handle);
@gbalke OK with the copy, but without the custom deleter we'll leak it.

2021-04-06 18:44 UTC, gbalke commented
CI up to `rclpy`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14269)](http://ci.ros2.org/job/ci_linux/14269/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9059)](http://ci.ros2.org/job/ci_linux-aarch64/9059/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11953)](http://ci.ros2.org/job/ci_osx/11953/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14368)](http://ci.ros2.org/job/ci_windows/14368/)

2021-04-07 07:35 UTC, ahcorde requested changes
Do you mind to add these changes https://github.com/ros2/rclpy/pull/756/commits/69394259676f8033022847e160ab298a83896c3f to your PR

2021-04-07 14:24 UTC, hidmic approved these changes
LGTM once @ahcorde's comments have been addressed

2021-04-07 18:49 UTC, gbalke commented
CI up to `rclpy`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14287)](http://ci.ros2.org/job/ci_linux/14287/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9076)](http://ci.ros2.org/job/ci_linux-aarch64/9076/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11971)](http://ci.ros2.org/job/ci_osx/11971/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14389)](http://ci.ros2.org/job/ci_windows/14389/)

2021-04-07 19:10 UTC, gbalke commented
CI up to `rclpy`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14289)](http://ci.ros2.org/job/ci_linux/14289/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9078)](http://ci.ros2.org/job/ci_linux-aarch64/9078/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11973)](http://ci.ros2.org/job/ci_osx/11973/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14391)](http://ci.ros2.org/job/ci_windows/14391/)

2021-04-07 22:37 UTC, sloretz commented
Something seems off with the diff on github. It looks like this PR includes all of #756 - the conversion of Publisher and Subscription. Is that intended?

2021-04-07 23:35 UTC, gbalke commented
> Do you mind to add these changes [6939425](https://github.com/ros2/rclpy/commit/69394259676f8033022847e160ab298a83896c3f) to your PR

@sloretz I thought that was what this was asking for?

2021-04-08 06:22 UTC, ahcorde commented
@greg the Publisher and Subscriber PR is in (in the `post_galactic_freeze` branch). I think you should remove the merge with the branch `pybind11-pubsub` (which is adding my commits too) and then merge your branch with `post_galactic_freeze`.

2021-04-08 17:27 UTC, gbalke commented
Did all the rebasing shenanigans.

CI up to `rclpy`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14301)](http://ci.ros2.org/job/ci_linux/14301/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9090)](http://ci.ros2.org/job/ci_linux-aarch64/9090/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11987)](http://ci.ros2.org/job/ci_osx/11987/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14405)](http://ci.ros2.org/job/ci_windows/14405/)

2021-04-08 19:04 UTC, ahcorde approved these changes

2021-04-08 19:54 UTC, merged