Add feature of wait for message (#953).
ros2/rclpy pull request #960
Opened 2022-06-22 09:59 UTC by llapx

Add feature of wait for message.

2022-06-27 03:33 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
> +def publish_message():
Move this function to class `TestWaitForMessage`

2022-06-27 03:33 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
> +        rclpy.init(context=context)
Common codes can be moved to `setUpClass()`

2022-06-27 03:33 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
> +        rclpy.shutdown(context=context)
Common code can be moved to `tearDownClass()`

2022-06-27 03:33 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
> +    time.sleep(1)
It is better to wait one subscriber connected.

2022-06-28 03:32 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +    timeout_sec=-1
wait_for_message of rclcpp use `time_to_wait`, so I update it to `time_to_wait`.

2022-06-28 06:03 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +    sigint_gc = SignalHandlerGuardCondition(context)
Because wait_for_message will conflict with spin_xxx, so it is necessary.

2022-06-28 06:27 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
> +        rclpy.shutdown(context=context)
Above 2 lines are done at tearDownClass

2022-06-28 06:27 UTC, Barry-Xu-2018 commented on rclpy/test/test_wait_for_message.py
>  class TestWaitForMessageTimeout(unittest.TestCase):
Does merge class TestWaitForMessage(unittest.TestCase) into one class ?

2022-07-04 02:10 UTC, Barry-Xu-2018 commented on rclpy/rclpy/wait_for_message.py
> +    sigint_gc = SignalHandlerGuardCondition(context)
It isn't related to executor.  
wait_set is created and managed in this function. SingalHandler seems to be needed.

2022-07-05 03:26 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +    sigint_gc = SignalHandlerGuardCondition(context)
Yes, needed.

2022-07-05 05:02 UTC, llapx commented
I see the test error happend with `test_timer`, which not related to this PR, so anybody can handle this?

2022-08-22 17:39 UTC, fujitatomoya reviewed
minor comments for doc section.

Note: this has the same problem with https://github.com/ros2/rclcpp/issues/1953#issuecomment-1159161872

2022-08-22 17:39 UTC, fujitatomoya commented on rclpy/rclpy/wait_for_message.py
> +    :time_to_wait: the timeout before returning
It would be nice to add units like second or mili-second.

```suggestion
    :time_to_wait: seconds to wait before returning
```

2022-08-22 17:39 UTC, fujitatomoya commented on rclpy/rclpy/wait_for_message.py
> +    :param topic: topic name you've defined
```suggestion
    :param topic: topic name to wait for message
```

2022-08-22 17:39 UTC, fujitatomoya commented on rclpy/rclpy/wait_for_message.py
> +    :param node: node you've created
```suggestion
    :param node: node to initialize the subscription on
```

2022-08-23 02:31 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +    :param topic: topic name you've defined
updated.

2022-08-23 02:31 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +    :param node: node you've created
updated.

2022-09-19 04:36 UTC, fujitatomoya commented
> Note: this has the same problem with https://github.com/ros2/rclcpp/issues/1953#issuecomment-1159161872

even though, this will provide the same function to `rclpy`. i will start the CI.

2022-09-19 04:46 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17317)](http://ci.ros2.org/job/ci_linux/17317/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11855)](http://ci.ros2.org/job/ci_linux-aarch64/11855/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17804)](http://ci.ros2.org/job/ci_windows/17804/)

2022-09-19 04:47 UTC, fujitatomoya approved these changes

2022-09-19 04:47 UTC, fujitatomoya commented
either @ivanpauno or @sloretz can you take a look at this?

2022-09-20 02:02 UTC, llapx commented
@fujitatomoya 

Can you provide failing logs so that I can fix it?

2022-11-12 18:41 UTC, Flova commented
Any updates on this?

2022-11-13 03:17 UTC, fujitatomoya commented
even with constraint of https://github.com/ros2/rclcpp/issues/1953#issuecomment-1155096374, i think this would be worth to add to rclpy.

2022-11-13 03:19 UTC, fujitatomoya commented
@llapx test for this new feature is failing, could you check?

2022-11-14 02:04 UTC, llapx commented
> @llapx test for this new feature is failing, could you check?

OK, I'll take a check.

2022-11-14 06:52 UTC, llapx commented
@fujitatomoya 

Updated, can you rerun your CI?

2022-11-14 14:21 UTC, adityapande-1995 commented
CI : 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17634)](http://ci.ros2.org/job/ci_linux/17634/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12182)](http://ci.ros2.org/job/ci_linux-aarch64/12182/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18209)](http://ci.ros2.org/job/ci_windows/18209/)

2022-11-14 18:06 UTC, fujitatomoya commented
@llapx still tests with this PR are flaky, can you address test failure on your local environment?

2022-11-15 02:09 UTC, llapx commented
@fujitatomoya 

Updated!

2022-11-15 17:13 UTC, adityapande-1995 commented
CI rerun :
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17643)](http://ci.ros2.org/job/ci_linux/17643/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12199)](http://ci.ros2.org/job/ci_linux-aarch64/12199/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18218)](http://ci.ros2.org/job/ci_windows/18218/)

2022-11-15 17:22 UTC, fujitatomoya requested changes

2022-11-15 17:22 UTC, fujitatomoya commented on rclpy/rclpy/wait_for_message.py
> +# Copyright 2022 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2022 Sony Group Corporation.
```

2022-11-15 17:22 UTC, fujitatomoya commented on rclpy/test/test_wait_for_message.py
> +# Copyright 2022 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2022 Sony Group Corporation.
```

2022-11-15 17:23 UTC, fujitatomoya commented
@llapx sorry, copyright should be adjusted. we do not need to rerun the CI against this change.

2022-11-16 01:42 UTC, llapx commented on rclpy/rclpy/wait_for_message.py
> +# Copyright 2022 Open Source Robotics Foundation, Inc.
updated.

2022-11-16 01:57 UTC, fujitatomoya commented
@adityapande-1995 can you do another review?

CC: @ivanpauno @clalancette

2022-11-16 03:59 UTC, adityapande-1995 approved these changes
Looks good !

2022-11-16 08:59 UTC, merged