Fix type annotations
ros2/rclpy pull request #974
Opened 2022-07-20 00:56 UTC by ihasdapie

// Do not merge (yet) //

This PR fixes/adds various type annotations in `rclpy`. So far I've only gone through and added `Optional[T]` to functions taking `None` as a default argument. I'm sure there's more than just that to fix -- I'Il be adding to this PR until `mypy` is happy and help would be appreciated :)

Signed-off-by: Brian Chen <brian.chen@openrobotics.org>

2022-07-25 06:33 UTC, fujitatomoya commented
+1 great effort 👍

2022-08-31 12:44 UTC, clalancette requested changes
This looks generally good to me, with the exception of the failing tests.  Once that is fixed, and CI is green, I'm happy to approve.

2022-08-31 12:44 UTC, clalancette commented on rclpy/rclpy/__init__.py
> +        executor: Optional[Executor] = None,
I'm pretty sure this change (and the related ones below) are what are causing CI to fail.  Maybe:

```suggestion
        executor: Optional['Executor'] = None,
```

will work?

2023-05-22 17:49 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18775)](http://ci.ros2.org/job/ci_linux/18775/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13299)](http://ci.ros2.org/job/ci_linux-aarch64/13299/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19516)](http://ci.ros2.org/job/ci_windows/19516/)

2023-05-22 17:58 UTC, sloretz approved these changes

2023-05-23 02:59 UTC, merged